name: Build APK and Notify Discord

on:
  push:
    tags:
      - "v*.*.*"
    branches-ignore:
      - main
      - l10n_dev_crowdin
      - custom-download-location
    paths-ignore:
      - '**/README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CI: true
      SKIP_BUILD: false

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download last SHA artifact
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: beta.yml
        name: last-sha
        path: .
      continue-on-error: true

    - name: Get Commits Since Last Run
      run: |
        if [ -f last_sha.txt ]; then
          LAST_SHA=$(cat last_sha.txt)
        else
          LAST_SHA=$(git rev-list --max-parents=0 HEAD)
        fi
        echo "Commits since $LAST_SHA:"
        COMMIT_LOGS=$(git log $LAST_SHA..HEAD --pretty=format:"● %s ~%an [֍](https://github.com/${{ github.repository }}/commit/%H)" --max-count=10)
        COMMIT_LOGS=$(echo "$COMMIT_LOGS" | sed -E 's/#([0-9]+)/[#\1](https:\/\/github.com\/rebelonion\/Dantotsu\/pull\/\1)/g')
        COMMIT_LOGS="${COMMIT_LOGS//'%'/'%25'}"
        COMMIT_LOGS="${COMMIT_LOGS//$'\n'/'%0A'}"
        COMMIT_LOGS="${COMMIT_LOGS//$'\r'/'%0D'}"
        echo "COMMIT_LOG=${COMMIT_LOGS}" >> $GITHUB_ENV
        echo "$COMMIT_LOGS"
        echo "$COMMIT_LOGS" > commit_log.txt
        BRANCH=${{ github.ref }}
        BRANCH=${BRANCH#refs/heads/}
        echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
      shell: /usr/bin/bash -e {0}
      env:
        CI: true

    - name: Save Current SHA for Next Run
      run: echo ${{ github.sha }} > last_sha.txt

    - name: Set variables
      run: |
        VER=$(grep -E -o 'versionName = ".*"' app/build.gradle.kts | sed -e 's/versionName = //g' | tr -d '"')
        SHA=${{ github.sha }}
        VERSION="${VER:-0.1.0}+${SHA:0:7}"
        echo "Version $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: List files in the directory
      run: ls -l

    - name: Setup JDK 21
      if: ${{ env.SKIP_BUILD != 'true' }}
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Cache Gradle dependencies
      if: ${{ env.SKIP_BUILD != 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: v1-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          v1-${{ runner.os }}-gradle-

    - name: Decode Keystore File
      if: ${{ github.repository == 'rebelonion/Dantotsu' }}
      run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > $GITHUB_WORKSPACE/key.keystore

    - name: Make gradlew executable
      if: ${{ env.SKIP_BUILD != 'true' }}
      run: chmod +x ./gradlew

    - name: Build with Gradle
      if: ${{ env.SKIP_BUILD != 'true' }}
      run: |
        if [ "${{ github.repository }}" == "rebelonion/Dantotsu" ]; then
          ./gradlew assembleGoogleAlpha \
            -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/key.keystore \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }};
        else
          ./gradlew assembleGoogleAlpha;
        fi

    - name: Generate APK checksum
      if: ${{ env.SKIP_BUILD != 'true' }}
      run: |
        APK_PATH="app/build/outputs/apk/google/alpha/app-google-alpha.apk"
        if [ -f "$APK_PATH" ]; then
          CHECKSUM=$(sha256sum "$APK_PATH" | awk '{print $1}')
          echo "CHECKSUM=$CHECKSUM" >> $GITHUB_ENV
          echo "SHA256: $CHECKSUM"
        fi

    - name: Upload a Build Artifact
      if: ${{ env.SKIP_BUILD != 'true' }}
      uses: actions/upload-artifact@v4
      with:
          name: Editotsu
          retention-days: 5
          compression-level: 9
          path: "app/build/outputs/apk/google/alpha/*.apk"

    - name: Create GitHub Pre-Release
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Editotsu ${{ github.ref_name }}
        body: ${{ env.COMMIT_LOG }}
        prerelease: true
        files: |
          app/build/outputs/apk/google/alpha/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Current SHA as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: last-sha
        path: last_sha.txt

    - name: Upload Commit log as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: commit-log
        path: commit_log.txt
